name: 测试Docker容器的使用
on:
  push:
#    tags:
#      - v[0-9]+.*

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: python:3.6.9
      env:
        NODE_ENV: development
      volumes:
        - /home/runner:/root/jade
    steps:
      - name: 查看Python版本
        run: python -V
      - name: 下载代码
        uses: actions/checkout@v3
      - name: 查看代码是否下载完成
        run: cat README.md
