name: 测试输出当前分支名称
on:
  push:
#    tags:
#      - v[0-9]+.*

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: 测试输出当前分支名称
        run: |
           echo ${GITHUB_REF#refs/heads/}
