name: 上传Release分支文件
on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  Ubuntu:
    name: 打包发布-操作系统版本:(${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ] # "ubuntu-18.04", "windows-latest","macos-latest"
    steps:
      - name: 克隆代码
        uses: actions/checkout@v3
      - name: 发布
        id: upload_try1
        continue-on-error: true
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files:
            "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # 给最高的权限

      - name: 尝试重新上传
        id: upload_try2
        if: steps.upload_try1.outcome == 'failure'
        continue-on-error: true
        uses: softprops/action-gh-release@v1
        with:
          files:
            "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # 给最高的权限