name: 测试LinuxArm架构和X64架构

on:
  push:
jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 aarch64
    steps:
      - uses: uraimo/run-on-arch-action@v2
        name: 建立aarch64环境
        id: build
        with:
          arch: aarch64
          distro: ubuntu18.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          base_image: jadehh/container_ocr:ascend-packing-1.0.3
          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            cd /artifacts
            echo $(uname -a) >> output.txt
            echo $(conda -V) >> ouput.txt

      - name: 获取输出
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          ls ${PWD}/artifacts/
          cat ${PWD}/artifacts/output.txt
