name: 测试LinuxArm架构和X64架构

on:
  push:


jobs:
  runs-on: ubuntu-latest

  strategy:
    matrix:
      arch:
        - arm
        - arm64
        - x86
        - x64

  env:
    BUILD_TARGET: liunux
    BUILD_ARCH: ${{ matrix.arch }}

    # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: 查看环境
      run: uname -a