name: 测试Docker容器的使用
on:
  push:
#    tags:
#      - v[0-9]+.*

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: 下载代码
        run: |
          git clone https://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@github.com/jadehh/jadehh_file.git
      - name: 设置git用户名和邮箱
        run: |
          git config --global user.email "jadehh@live.com"
          git config --global user.name "jade"
      - name: 新建分支
        run: |
          cd jadehh_file
          git branch test
          git checkout test
      - name: 新建文件
        run: |
          cd jadehh_file
          touch test.py
          git add test.py
      - name: 提交
        run: |
          cd jadehh_file
          git commit -m '更新分支'
          git push  origin test








