name: 测试Docker容器的使用
on:
  push:
#    tags:
#      - v[0-9]+.*
permissions: write-all

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: 输出分支名称
        run: echo ${{ secrets.GH_PAT }}
      - name: 下载代码
        uses: actions/checkout@v3
        with:
          repository: jadehh/jadehh_file
      - name: 新建分支
        run: |
          git config --global user.email "jadehh@live.com"
          git config --global user.name "jade"
          touch test.py
          git add test.py
          git commit -m '上传test分支'
      - name: 查看当前分支信息
        run: |
          ls -l
      - name: 上传分支
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: main
          repository: jadehh/jadehh_file
          force: true
          directory: .
        env:
          GITHUB_ACTOR: jadehh

