name: 测试LinuxArm架构和X64架构

on:
  push:


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, [linux, ARM64]]
    steps:
      - name: 查看系统环境
        shell: pwsh
        run: |
          uname -a
