name: 测试Docker容器的使用
on:
  push:
#    tags:
#      - v[0-9]+.*

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: 下载代码
        uses: actions/checkout@v3
        with:
          repository: jadehh/jadehh_file
          ref: main
          path: code
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
      - name: 输出分支名称
        run: echo ${{ github.ref }}
      - name: 新建分支
        run: |
          cd code
          git branch test
          git checkout test
          touch test.py
          git add test.py
          git commit -m '上传test分支'
      - name: 上传分支
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: test


