name: 测试Docker容器的使用
on:
  push:
#    tags:
#      - v[0-9]+.*

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: python:3.6.9
      env:
        NODE_ENV: development
      volumes:
        - ${PWD}:/root/jade
    steps:
      - name: 写入Python环境
        run: echo $(python -v) >> output.txt

      - name: 查看Python版本
        run: cat output.txt
